In [1]:
import pandas as pd
df = pd.read_csv('/content/adult_with_headers.csv')
df.head(10)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship    race  \
0           Never-married        Adm-clerical   Not-in-family   White   
1      Married-civ-spouse     Exec-managerial         Husband   White   
2                Divorced   Handlers-cleaners   Not-in-family   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
4      Married-civ-spouse      Prof-specialty            Wife   Black   
5      Married-civ-spouse     Exec-managerial            Wife   White   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
8           Never-married      Prof-specialty   Not-in-family   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       sex  capital_gain  capital_loss  hours_per_week  native_country  income  
0     Male          2174             0              40   United-States   <=50K  
1     Male             0             0              13   United-States   <=50K  
2     Male             0             0              40   United-States   <=50K  
3     Male             0             0              40   United-States   <=50K  
4   Female             0             0              40            Cuba   <=50K  
5   Female             0             0              40   United-States   <=50K  
6   Female             0             0              16         Jamaica   <=50K  
7     Male             0             0              45   United-States    >50K  
8   Female         14084             0              50   United-States    >50K  
9     Male          5178             0              40   United-States    >50K

In [2]:
df.shape

(32561, 15)

In [3]:
df['workclass'].unique()


array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [4]:
import numpy as np
df.replace(' ?',np.nan,inplace=True)


In [5]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [6]:
cat_col = ['native_country','occupation', 'workclass']
df[cat_col] = df[cat_col].fillna('Unknown')

In [7]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [8]:
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64 
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64 
 11  capital_loss    32561 non-null  int64 
 12  hours_per_week  32561 non-null  int64 
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [10]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler
num_cols = df.select_dtypes(include = ['int64','float64']).columns
num_cols

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')

In [12]:
st_scaled = StandardScaler()
df_st_scaled = st_scaled.fit_transform(df[num_cols])
print(df_st_scaled)

[[ 0.03067056 -1.06361075  1.13473876  0.1484529  -0.21665953 -0.03542945]
 [ 0.83710898 -1.008707    1.13473876 -0.14592048 -0.21665953 -2.22215312]
 [-0.04264203  0.2450785  -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 ...
 [ 1.42360965 -0.35877741 -0.42005962 -0.14592048 -0.21665953 -0.03542945]
 [-1.21564337  0.11095988 -0.42005962 -0.14592048 -0.21665953 -1.65522476]
 [ 0.98373415  0.92989258 -0.42005962  1.88842434 -0.21665953 -0.03542945]]


In [13]:
mm_scaled = MinMaxScaler()
df_mm_scaled = mm_scaled.fit_transform(df[num_cols])
df_mm_scaled

array([[0.30136986, 0.0443019 , 0.8       , 0.02174022, 0.        ,
        0.39795918],
       [0.45205479, 0.0482376 , 0.8       , 0.        , 0.        ,
        0.12244898],
       [0.28767123, 0.13811345, 0.53333333, 0.        , 0.        ,
        0.39795918],
       ...,
       [0.56164384, 0.09482688, 0.53333333, 0.        , 0.        ,
        0.39795918],
       [0.06849315, 0.12849934, 0.53333333, 0.        , 0.        ,
        0.19387755],
       [0.47945205, 0.18720338, 0.53333333, 0.1502415 , 0.        ,
        0.39795918]])

**Scenarios where each scaling technique is preferred and why?**
Standard Scaling:
- Used when data should be centered at mean 0 and variance 1.
- Works best for algorithms assuming Gaussian distribution:
  (Logistic Regression, Linear Regression, SVM, PCA)

Min-Max Scaling:
- Compresses values to range 0–1.
- Useful for distance-based models:
  (KNN, Neural Networks, Clustering)

In [14]:
cat_cols = df.select_dtypes(include = ['object']).columns
cat_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [15]:
for col in cat_cols:
  print(col, ":", df[col].nunique())

workclass : 9
education : 16
marital_status : 7
occupation : 15
relationship : 6
race : 5
sex : 2
native_country : 42
income : 2


In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
one_hot_cols = []
label_cols = []

for col in cat_cols:
  if df[col].nunique() <5:
    one_hot_cols.append(col)
  else:
    label_cols.append(col)

  df_encoded = pd.get_dummies(df, columns = one_hot_cols, drop_first = True)#drop_first=True kept the column count the same.

  le = LabelEncoder()
  for col in label_cols:
    df_encoded[col] = le.fit_transform(df[col])
df_encoded.head(10)



age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          6   77516          9             13               4   
1   50          5   83311          9             13               2   
2   38          3  215646         11              9               0   
3   53          3  234721          1              7               2   
4   28          3  338409          9             13               2   
5   37          3  284582         12             14               2   
6   49          3  160187          6              5               3   
7   52          5  209642         11              9               2   
8   31          3   45781         12             14               4   
9   42          3  159449          9             13               2   

   occupation  relationship  race  capital_gain  capital_loss  hours_per_week  \
0           0             1     4          2174             0              40   
1           3             0     4             0             0              13   
2           5             1     4             0             0              40   
3           5             0     2             0             0              40   
4           9             5     2             0             0              40   
5           3             5     4             0             0              40   
6           7             1     2             0             0              16   
7           3             0     4             0             0              45   
8           9             1     4         14084             0              50   
9           3             0     4          5178             0              40   

   native_country  sex_ Male  income_ >50K  
0              38       True         False  
1              38       True         False  
2              38       True         False  
3              38       True         False  
4               4      False         False  
5              38      False         False  
6              22      False         False  
7              38       True          True  
8              38      False          True  
9              38       True          True

In [17]:
print("\nOriginal Shape:", df.shape)
print("Encoded Shape:", df_encoded.shape)


Original Shape: (32561, 15)
Encoded Shape: (32561, 15)


In [18]:
df['hours_per_week'] = pd.cut(df['hours_per_week'], bins = 3, labels = ['low', 'medium', 'high'])
df.head(10)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship    race  \
0           Never-married        Adm-clerical   Not-in-family   White   
1      Married-civ-spouse     Exec-managerial         Husband   White   
2                Divorced   Handlers-cleaners   Not-in-family   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
4      Married-civ-spouse      Prof-specialty            Wife   Black   
5      Married-civ-spouse     Exec-managerial            Wife   White   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
8           Never-married      Prof-specialty   Not-in-family   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       sex  capital_gain  capital_loss hours_per_week  native_country  income  
0     Male          2174             0         medium   United-States   <=50K  
1     Male             0             0            low   United-States   <=50K  
2     Male             0             0         medium   United-States   <=50K  
3     Male             0             0         medium   United-States   <=50K  
4   Female             0             0         medium            Cuba   <=50K  
5   Female             0             0         medium   United-States   <=50K  
6   Female             0             0            low         Jamaica   <=50K  
7     Male             0             0         medium   United-States    >50K  
8   Female         14084             0         medium   United-States    >50K  
9     Male          5178             0         medium   United-States    >50K

In [22]:
df['age_group'] = pd.cut(df['age'], bins=3, labels=['Young', 'Adult', 'Senior'])
df.head(10)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship    race  \
0           Never-married        Adm-clerical   Not-in-family   White   
1      Married-civ-spouse     Exec-managerial         Husband   White   
2                Divorced   Handlers-cleaners   Not-in-family   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
4      Married-civ-spouse      Prof-specialty            Wife   Black   
5      Married-civ-spouse     Exec-managerial            Wife   White   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
8           Never-married      Prof-specialty   Not-in-family   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       sex  capital_gain  capital_loss hours_per_week  native_country  income  \
0     Male          2174             0         medium   United-States   <=50K   
1     Male             0             0            low   United-States   <=50K   
2     Male             0             0         medium   United-States   <=50K   
3     Male             0             0         medium   United-States   <=50K   
4   Female             0             0         medium            Cuba   <=50K   
5   Female             0             0         medium   United-States   <=50K   
6   Female             0             0            low         Jamaica   <=50K   
7     Male             0             0         medium   United-States    >50K   
8   Female         14084             0         medium   United-States    >50K   
9     Male          5178             0         medium   United-States    >50K   

  age_group  
0     Young  
1     Adult  
2     Young  
3     Adult  
4     Young  
5     Young  
6     Adult  
7     Adult  
8     Young  
9     Adult

In [23]:
df['capital_gain_log'] = np.log1p(df['capital_gain'])

In [24]:
print("Original Skewness:", df['capital_gain'].skew())
print("Log Skewness:", df['capital_gain_log'].skew())


Original Skewness: 11.953847687699799
Log Skewness: 3.096143524467517


In [ ]:
from sklearn.ensemble import IsolationForest

iso = IsolationForest(n_estimators=200, contamination=0.02, random_state=42)

# Fit on numeric features
numeric_cols = df_encoded.select_dtypes(include=['int64','float64']).columns
iso_pred = iso.fit_predict(df_encoded[numeric_cols])

# Mark outliers
df_encoded['is_outlier'] = (iso_pred == -1).astype(int)

# Remove outliers
df_no_outliers = df_encoded[df_encoded['is_outlier'] == 0].drop(columns=['is_outlier'])


In [ ]:
import ppscore as pps

pps_matrix = pps.predictors(df_no_outliers, 'income')
pps_matrix.sort_values(by='ppscore', ascending=False).head(10)
